#!/usr/bin/env php

<?php
require_once __DIR__.'/vendor/autoload.php';

$command = $argv[1];
$args = array_slice($argv, 2);

$commands = new \App\CommandList();
$commands->addCommand('download', new \App\DownloadCommand());
$commands->addCommand('schedule', new \App\ScheduleCommand());
$commands->addCommand('install', new \App\InstallCommand());
$commands->runCommand($command, $args);